# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(411, 405)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Microsoft YaHei UI Light\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 190, 61, 22))
        self.label.setObjectName("label")
        self.lbLogin = QtWidgets.QLineEdit(self.centralwidget)
        self.lbLogin.setGeometry(QtCore.QRect(70, 220, 261, 31))
        self.lbLogin.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(219, 212, 255);\n"
"border-radius: 5px;\n"
"")
        self.lbLogin.setObjectName("lbLogin")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 260, 71, 22))
        self.label_2.setObjectName("label_2")
        self.lbPass = QtWidgets.QLineEdit(self.centralwidget)
        self.lbPass.setGeometry(QtCore.QRect(70, 290, 261, 31))
        self.lbPass.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(219, 212, 255);\n"
"border-radius: 5px;\n"
"")
        self.lbPass.setObjectName("lbPass")
        self.pbEntry = QtWidgets.QPushButton(self.centralwidget)
        self.pbEntry.setGeometry(QtCore.QRect(70, 350, 261, 31))
        self.pbEntry.setStyleSheet("background-color: rgb(219, 212, 255);\n"
"border: 2px solid rgb(219, 212, 255);\n"
"border-radius: 5px;\n"
"")
        self.pbEntry.setObjectName("pbEntry")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, -10, 411, 181))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 13pt \"Microsoft YaHei UI Light\";\n"
"background-color: rgb(219, 212, 255);\n"
"margin: 0 0 0 20;")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Авторизация"))
        self.label.setText(_translate("MainWindow", "Логин:"))
        self.label_2.setText(_translate("MainWindow", "Пароль:"))
        self.pbEntry.setText(_translate("MainWindow", "Войти"))
        self.label_4.setText(_translate("MainWindow", "Программный комплекс для\n"
"прогнозирования качества\n"
"полимерной пленки с\n"
"использованием выборочной\n"
"нейронной сети"))
