# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ProrgessWindow(object):
    def setupUi(self, ProrgessWindow):
        ProrgessWindow.setObjectName("ProrgessWindow")
        ProrgessWindow.resize(465, 110)
        ProrgessWindow.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.centralwidget = QtWidgets.QWidget(ProrgessWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 30, 401, 41))
        self.progressBar.setStyleSheet("QProgressBar::chunk {\n"
"    background-color: rgb(219, 212, 255);\n"
"    transparent: 10;\n"
"    width: 20px;\n"
"    margin: 0.5px;\n"
"}\n"
"QProgressBar{\n"
"    border: 2px solid rgb(219, 212, 255);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"\n"
"")
        self.progressBar.setMaximum(0)
        self.progressBar.setProperty("value", -1)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        ProrgessWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ProrgessWindow)
        QtCore.QMetaObject.connectSlotsByName(ProrgessWindow)

    def retranslateUi(self, ProrgessWindow):
        _translate = QtCore.QCoreApplication.translate
        ProrgessWindow.setWindowTitle(_translate("ProrgessWindow", "Прогнозирование данных..."))
