# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\gnipk\OneDrive\Рабочий стол\admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 673)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 10pt \"Microsoft YaHei UI Light\";\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1171, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 14pt \"Microsoft YaHei UI Light\";\n"
"background-color: rgb(164, 166, 165);\n"
"margin: 0 0 0 20;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.pbPredict = QtWidgets.QPushButton(self.centralwidget)
        self.pbPredict.setGeometry(QtCore.QRect(620, 620, 321, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbPredict.setFont(font)
        self.pbPredict.setStyleSheet("background-color: rgb(164, 166, 165);\n"
"border: 2px solid rgb(164, 166, 165);\n"
"border-radius: 5px;")
        self.pbPredict.setObjectName("pbPredict")
        self.pbChart = QtWidgets.QPushButton(self.centralwidget)
        self.pbChart.setGeometry(QtCore.QRect(620, 520, 321, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbChart.setFont(font)
        self.pbChart.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(164, 166, 165);\n"
"border-radius: 5px;\n"
"")
        self.pbBack = QtWidgets.QPushButton(self.centralwidget)
        self.pbBack.setGeometry(QtCore.QRect(850, 10, 121, 35))
        self.pbBack.setIcon(QtGui.QIcon('imgs/pbBack.ico'))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pbBack.setFont(font)
        self.pbBack.setStyleSheet("background-color: rgb(164, 166, 165);\n"
                                  "border: 2px solid rgb(164, 166, 165);\n"
                                  "border-radius: 5px;")
        self.pbBack.setText("")
        self.pbBack.setObjectName("pbBack")
        self.pbChart.setObjectName("pbChart")
        self.ROC = QtWidgets.QPushButton(self.centralwidget)
        self.ROC.setGeometry(QtCore.QRect(620, 570, 321, 35))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ROC.setFont(font)
        self.ROC.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: 2px solid rgb(164, 166, 165);\n"
"border-radius: 5px;\n"
"")
        self.ROC.setObjectName("ROC")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 80, 1121, 431))
        self.tabWidget.setStyleSheet("QTabWidget::tab-bar {\n"
                                     "    left: 5px; /* move to the right by 5px */\n"
                                     "}\n"
                                     "\n"
                                     "/* Style the tab using the tab sub-control. Note that\n"
                                     "    it reads QTabBar _not_ QTabWidget */\n"
                                     "QTabBar::tab {\n"
                                     "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                     "                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
                                     "                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
                                     "    border: 2px solid #C4C4C3;\n"
                                     "    border-bottom-color: #C2C7CB; /* same as the pane color */\n"
                                     "    min-width: 8ex;\n"
                                     "    padding: 2px;\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected, QTabBar::tab:hover {\n"
                                     "    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
                                     "                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
                                     "                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:selected {\n"
                                     "    border-color: #9B9B9B;\n"
                                     "    border-bottom-color: #C2C7CB; /* same as pane color */\n"
                                     "}\n"
                                     "\n"
                                     "QTabBar::tab:!selected {\n"
                                     "    margin-top: 2px; /* make non-selected tabs look smaller */\n"
                                     "}")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tabModel = QtWidgets.QWidget()
        self.tabModel.setObjectName("tabModel")
        self.tableWidget = QtWidgets.QTableWidget(self.tabModel)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 921, 361))
        self.tableWidget.setAutoFillBackground(False)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.tabModel, "")
        self.tabParameter = QtWidgets.QWidget()
        self.tabParameter.setObjectName("tabParameter")
        self.tabWidget.addTab(self.tabParameter, "")
        self.tabTypeParameter = QtWidgets.QWidget()
        self.tabTypeParameter.setObjectName("tabTypeParameter")
        self.tabWidget.addTab(self.tabTypeParameter, "")
        self.tabUnit = QtWidgets.QWidget()
        self.tabUnit.setObjectName("tabUnit")
        self.tabWidget.addTab(self.tabUnit, "")
        self.tabCoefficient = QtWidgets.QWidget()
        self.tabCoefficient.setObjectName("tabCoefficient")
        self.tabWidget.addTab(self.tabCoefficient, "")
        self.tabTypeCoefficient = QtWidgets.QWidget()
        self.tabTypeCoefficient.setObjectName("tabTypeCoefficient")
        self.tabWidget.addTab(self.tabTypeCoefficient, "")
        self.tabModelParameter = QtWidgets.QWidget()
        self.tabModelParameter.setObjectName("tabModelParameter")
        self.tabWidget.addTab(self.tabModelParameter, "")
        self.tabModelCoefficient = QtWidgets.QWidget()
        self.tabModelCoefficient.setObjectName("tabModelCoefficient")
        self.tabWidget.addTab(self.tabModelCoefficient, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 520, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(75, 550, 171, 16))
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(53, 580, 201, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(43, 610, 201, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 640, 211, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 520, 331, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(260, 550, 331, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(260, 580, 331, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(260, 610, 331, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(260, 640, 331, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Редактированеие БД"))
        self.label.setText(_translate("MainWindow", "Редактированеие БД"))
        self.pbPredict.setText(_translate("MainWindow", "Удалить"))
        self.pbChart.setText(_translate("MainWindow", "Добавить"))
        self.ROC.setText(_translate("MainWindow", "Изменить"))
        self.tableWidget.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModel), _translate("MainWindow", "Модели"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabParameter), _translate("MainWindow", "Параметры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTypeParameter), _translate("MainWindow", "Типы параметров"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUnit), _translate("MainWindow", "Единицы измерения"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCoefficient), _translate("MainWindow", "Коэффициенты модели"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTypeCoefficient), _translate("MainWindow", "Тип коэффициента"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModelParameter), _translate("MainWindow", "Параметры модели"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabModelCoefficient), _translate("MainWindow", "Коэффициенты модели"))
        self.label_2.setText(_translate("MainWindow", "Код параметра"))
        self.label_3.setText(_translate("MainWindow", "Имя параметра на русском"))
        self.label_4.setText(_translate("MainWindow", "Имя параметра на английском"))
        self.label_5.setText(_translate("MainWindow", "Нижнее регламентное значение"))
        self.label_6.setText(_translate("MainWindow", "Верхнее регламентное значение"))
